import fs from "fs";
import path from "path";

import puppeteer from "puppeteer";
import { NextResponse } from "next/server";

export async function POST(req) {
  try {
    const { markdownContent, title } = await req.json();

    // Load styles and logo
    const cssPath = path.resolve("./styles/pdfStyles.css");
    const logoPath = path.resolve("./public/logo.png");

    if (!fs.existsSync(cssPath) || !fs.existsSync(logoPath)) {
      throw new Error("Required files are missing.");
    }

    const styles = fs.readFileSync(cssPath, "utf-8");
    const logoBase64 = fs.readFileSync(logoPath, "base64");

    // Convert Markdown to HTML
    const marked = (await import("marked")).marked;
    const htmlContent = `
    <html>
      <head>
        <style>${styles}</style>
      </head>
      <body>
        <main>
          <h1>${title}</h1>
          ${marked(markdownContent)}
        </main>
      </body>
    </html>`;

    // Use CHROME_PATH from the Netlify Chrome plugin
    const chromePath = process.env.CHROME_PATH;

    if (!chromePath) {
      throw new Error("CHROME_PATH environment variable is not set.");
    }

    const browser = await puppeteer.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
      //executablePath: chromePath, // Use the path provided by the plugin
      headless: true,
    });

    const page = await browser.newPage();

    await page.setContent(htmlContent, { waitUntil: "networkidle2" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `
       <div style="font-size: 12px; text-align: right; width:100%; padding-right: 50px;">
          <span>Generated by DriftDraft.App</span>
          <img src="data:image/png;base64,${logoBase64}" style="height: 20px; vertical-align: middle;" />
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 12px; text-align: center; width:100%;">
          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `,
      margin: { top: "40mm", bottom: "30mm" },
    });

    await browser.close();

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${title.replace(/[^a-z0-9]/gi, "_").toLowerCase()}.pdf"`,
      },
    });
  } catch (error) {
    console.error("Error generating PDF:", error);

    return new NextResponse(
      JSON.stringify({ message: "Failed to generate PDF", error: error.message }),
      { status: 500 }
    );
  }
}
