import fs from "fs";
import path from "path";

import puppeteer from "puppeteer";
import { NextResponse } from "next/server";

import logger from "@/lib/logger";

export async function POST(req) {
  try {
    const { markdownContent, title } = await req.json();

    // Read the external CSS file
    const cssPath = path.resolve("./styles/pdfStyles.css");
    const styles = fs.readFileSync(cssPath, "utf-8");

    const logoPath = path.resolve("./public/logo.png");
    const logoBase64 = fs.readFileSync(logoPath, "base64");


    logger.debug("Generating PDF from Markdown content:", markdownContent);
    logger.debug("Type of markdownContent:", typeof markdownContent);

    // Convert Markdown to HTML
    const marked = (await import("marked")).marked;
    const htmlContent = `
     <html>
      <head>
        <style>
        ${styles}
        </style>
      </head>
      <body>
        <main>
          <h1>${title}</h1>
          ${marked(markdownContent)}
        </main>
      </body>
    </html>`;

    // Launch Puppeteer
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    // Set the HTML content
    await page.setContent(htmlContent);

    // Generate the PDF
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      displayHeaderFooter: true, // Enables header and footer
      headerTemplate: `
        <div style="font-size: 12px; width: 100%; text-align: right; padding-right: 50px;">
          <span style="margin-left: 10px; color:"#2E0219">Generated by <a href="https://driftdraft.app" target="_blank" style="text-decoration:none; color:#028090">DriftDraft.App</a></span>
          <img src="data:image/png;base64,${logoBase64}" alt="Logo" style="height: 20px; vertical-align: middle;" />
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 12px; width: 100%; text-align: center;">
          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      `,
      margin: {
        top: "40mm", // Space for the header
        bottom: "30mm", // Space for the footer
      },
    });

    await browser.close();

    // Return the PDF as a response
    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'attachment; filename="generated.pdf"',
      },
    });
  } catch (error) {
    console.error("Error generating PDF:", error);

    return NextResponse.json(
      { message: "Failed to generate PDF", error: error.message },
      { status: 500 }
    );
  }
}
